### ISSUE TITLE
Clustering does not work

### ISSUE THREAD

**Issue by VictorJosso** [linuxserver-archive/docker-openvpn-as#115]
## Expected Behavior
I have built a cluster with two VPN servers. They are available at vpn.domain.fr and vpn.bis.domain.fr. When I log into the admin panel, I am supposed to be able to manage all the servers. 

## Current Behavior
I can only manage the server to which I connect (for example, vpn.domain.fr:943 will only let me manage the server serving this address). I have an error saying `[Errno 2] No such file or directory: '/usr/local/openvpn_as/etc/ssl-api/ca.crt'` See the image below:

![screenshot-vpnadmin-2020 05 04-18_20_22](https://user-images.githubusercontent.com/36574511/81065370-9f4fa380-8edb-11ea-87a1-09b63032c2ba.png)

## Steps to Reproduce

1. Install the linuxserver/openvpn-as on two servers + run a MySQL container
2. Create a cluster on the first container, and join this cluster with the other one
3. Connect to the admin panel of any server

## Environment
**OS:**  Openmediavault 5.4.2
**CPU architecture:** x86_64      
**How docker service was installed:**  OMV web interface.

## Command used to create docker container

```
docker create \
  --name=vpn \
  --cap-add=NET_ADMIN \
  -e PUID=1001 \
  -e PGID=100 \
  -e TZ=Europe/Paris \
  -p 943:943 \
  -p 9443:9443 \
  -p 1194:1194/udp \
  -p 945:945
  -v /srv/dev-disk-by-label.....:/config \
  --restart unless-stopped \
  linuxserver/openvpn-as
```

## Docker logs

Nothing about that

**Comment by aptalca** [comment]
#149
