### ISSUE TITLE
After starting container i got ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by dridi93** [linuxserver-archive/docker-openvpn-as#117]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Get login web page

## Current Behavior

Got ERR_EMPTY_RESPONSE

## Steps to Reproduce

1. Make docker-compose file
2. Run docker compose
3. Open to url: https://IP:943/admin

## Environment

**OS:**     Ubuntu 18.04
**CPU architecture:** x86_64      
**How docker service was installed:**      Docker-Compose

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
    volumes:
      - ./openvpn-as/config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped

## Docker logs

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-time: executing... ,
,
Current default time zone: 'Europe/Paris',
Local time is now:      Tue May 12 14:40:17 CEST 2020.,
Universal Time is now:  Tue May 12 12:40:17 UTC 2020.,

[cont-init.d] 20-time: exited 0.,
[cont-init.d] 30-config: executing... ,
existing data found, reinstalling openvpn-as,
backing up certs.db,
backing up cluster.db,
backing up config.db,
backing up config_local.db,
backing up log.db,
backing up notification.db,
backing up userprop.db,
backing up as.conf,
Selecting previously unselected package openvpn-as-bundled-clients.,
(Reading database ... 15006 files and directories currently installed.),
Preparing to unpack /openvpn/openvpn-clients.deb ...,
Unpacking openvpn-as-bundled-clients (5) ...,
Setting up openvpn-as-bundled-clients (5) ...,
Selecting previously unselected package openvpn-as.,
(Reading database ... 15019 files and directories currently installed.),
Preparing to unpack /openvpn/openvpn.deb ...,
Unpacking openvpn-as (2.8.1-3ae74700-Ubuntu16) ...,
Setting up openvpn-as (2.8.1-3ae74700-Ubuntu16) ...,
Automatic configuration failed, see /usr/local/openvpn_as/init.log,
You can configure manually using the /usr/local/openvpn_as/bin/ovpn-init tool.,
restoring certs.db,
restoring cluster.db,
restoring config.db,
restoring config_local.db,
restoring log.db,
restoring notification.db,
restoring userprop.db,
restoring as.conf,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 40-openvpn-init: executing... ,
[cont-init.d] 40-openvpn-init: exited 0.,
[cont-init.d] 50-interface: executing... ,
MOD Default {} {},
MOD Default {} {},
MOD Default {} {},
MOD Default {} {},
[cont-init.d] 50-interface: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,

**Comment by aptalca** [comment]
Try an incognito window

**Comment by dridi93** [comment]
@aptalca incognito window don't resolve the problem

**Comment by tenpaiyomi** [comment]
I'm experiencing this behavior as well.  No errors, everything seems to start up fine, but attempting to hit the admin UI in a web browser gives an immediate `The connection was reset` response.  Doing a `curl` on the server gives an immediate `curl: (52) Empty reply from server`

**Comment by uruloki** [comment]
Also experiencing this behavior. DokuWiki container on port 8000 is up and accessible. Also tried without port mapping (-p 943 -p 9443 -p 1194/udp) and received the same error.

**Comment by twissell-** [comment]
I'm getting the same error.

**Comment by Poltergeisen** [comment]
I am also getting this error. Any idea what is going on?

**Comment by aptalca** [comment]
`me too` is not going to get anyone closer to the bottom of this. There are various reasons why the server may be rejecting the connection. 

Post your host os, arch (hw if applicable), full docker logs and the command you used to create the container

**Comment by tomholford** [comment]
Also experiencing this issue. Per @aptalca's feedback, will try to include helpful info.

Trying to run this container on the latest version of [CapRover](https://github.com/caprover/caprover) (1.7.1). [Here is a link to the config template](https://github.com/caprover/one-click-apps/pull/222/files#diff-301057ca066e180267974d90e549b21a) that I am working on in this PR https://github.com/caprover/one-click-apps/pull/222, you can see the docker-compose variables being used there. For what it's worth, it is using all the defaults as outlined on the Docker Hub page for the image.

Also worth mentioning, I have tried this with a few different versions of the image to see if it was introduced recently, experiencing the same issue with all three of these:
```
2.8.5-f4ad562b-Ubuntu18-ls77
2.8.3-f28d2eae-Ubuntu18-ls66
2.8.3-f28d2eae-Ubuntu18-ls64
```
## screenshots
__container has ports exposed__
![image](https://user-images.githubusercontent.com/16504501/87036397-b7b6a400-c225-11ea-8275-e9ae9f475a54.png)

__curling `localhost:943`__
![image](https://user-images.githubusercontent.com/16504501/87036473-d5840900-c225-11ea-9280-814c0099e96e.png)

Hope this helps!

**Comment by aptalca** [comment]
1. Don't change the interface var in bridge networking
2. Use https

**Comment by douglasjunior** [comment]
Same problem here, on `Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64`.

```
# curl http://127.0.0.1:943/admin
curl: (52) Empty reply from server

# curl https://127.0.0.1:9443/admin
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:9443 
```

My `docker-compose.yml`:
```yml
version: '3'
services:
  openvpn-as:
    image: linuxserver/openvpn-as:2.8.6-916f8e7d-Ubuntu18-ls87
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
      #- INTERFACE=eth0 #optional
    volumes:
      - /root/openvpn/config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
```

Container logs:
```
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing... 
[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-openvpn-init: executing... 
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing... 
MOD Default {} {}
MOD Default {} {}
MOD Default {} {}
MOD Default {} {}
[cont-init.d] 50-interface: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Listing interface with `ip r`
```
ip r
default via x.x.x.x dev eth0 onlink 
x.x.x.x/16 dev docker0 proto kernel scope link src x.x.x.x linkdown 
x.x.x.x/16 dev br-d1385e27f015 proto kernel scope link src x.x.x.x 
x.x.x.x/24 dev eth0 proto kernel scope link src x.x.x.x
```

Firewall rules with `iptables --list`
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.18.0.2           tcp dpt:https
ACCEPT     tcp  --  anywhere             172.18.0.2           tcp dpt:http
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:9443
ACCEPT     udp  --  anywhere             172.18.0.3           udp dpt:openvpn
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:943

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
# Warning: iptables-legacy tables present, use iptables-legacy to see them
```
