### ISSUE TITLE
confdba tool does not seem to work

### ISSUE THREAD

**Issue by SubrataM3** [linuxserver-archive/docker-openvpn-as#128]
------------------------------

## Expected Behavior
I think` /usr/local/openvpn_as/scripts/confdba` is supposed to update configuration which it does not.

## Current Behavior
Alright, So i read this script `root/etc/cont-init.d/50-interface` . by default interface is set to eth0 if no env variable is passed.
But after the initial install when I log in to the admin panel, I see that its listening to all the interfaces rather than just eth0.

So I checked the sqlite databases directly in `/config/etc/db` and found that `confdba` tool is updating/inserting values in the `config.db` which is not visible in the admin panel and also not in use by the openvpn server (I suppose). Making changes via the admin panel updates the `config_local.db`.

I am not sure if this is normal behavior if not this can be probably be fixed by passing --db=sqlite:////config/etc/db/config_local.db, another option is sacli tool, but that requires openvpn to be running.

## Steps to Reproduce
NA

## Environment
NA

## Command used to create docker container (run/create/compose/screenshot)
NA

## Docker logs
NA

**Comment by aptalca** [comment]
Iirc interface variable only changes on which interface the admin portal is accessible. The other gui setting is for which interface to listen on for vpn connections.

Also it is my understanding that config.db contains the original/default values whereas the local one contains all user changes and the local one supersedes the main one in use, for any value that's been set in there.

The way these two databases are used is determined and controlled by openvpn and we make no changes to that behavior.

**Comment by SubrataM3** [comment]
I understand what you said, But then the script `root/etc/cont-init.d/50-interface`  is not so useful because if you login to the admin panel right after container creation, the values are it supposed to changed are not changed. 
actually those interface change does not matter much, but I wanted to change openvpn tcp and udp port on startup and I found confdba is not working.
I think config.db is copied to _local.db on first run and not used afterwards.
![image](https://user-images.githubusercontent.com/15718377/87430259-94636e80-c602-11ea-9646-cd9a1a82fb96.png)

If someone wants to customize anything automatically, then the local db needs to be modified, so I thought it might be helpful to post. :-)
Thanks.

**Comment by aptalca** [comment]
I don't think you follow. The setting you're referring to in the gui is not the same setting we set in the init file.
Don't overthink it. Everything is working as it should.
You can change the tcp and udp ports for vpn access in the gui and that works just fine. You just have to change your port mappings as well.

If you're trying to customize the init file, then that's not something we support.

**Comment by aptalca** [comment]
#149
