### ISSUE TITLE
(option doesn't work) Allow access from these private subnets to all VPN client IP addresses and subnets

### ISSUE THREAD

**Issue by karezza** [linuxserver-archive/docker-openvpn-as#140]
[linuxserverurl]: https://linuxserver.io

## Desired Behavior
For your consideration, an option that allows a vpn client to be reachable from the lan it has gained access to via the vpn.  E.g. I'd like to develop flutter apps and from my network would like to have access to a mobile device which is joined via a vpn.  In summary, when a device joins via vpn I'd like it to get an ip address on the local lan and be reachable / fully joined to the network.

## Current Behavior
Openvpn gui has a way to configure and enable this ability but it doesn't appear to work. See CONFIGURATION -> VPN SETTINGS -> Allow access from these private subnets to all VPN client IP addresses and subnets.  -- I think the problem may be the vpn is using a docker network type of 'bridge' which seems to stop the ability of openvpn from enabling the ability to reach a vpn client from the network it has gained access to via the vpn, if this were set to host I think it would work (not sure how to do this).

## Alternatives Considered
I've tried for 13 hours today to get this to work.  Every variation of options within openvpn that I could think of, tried adding routing to my home pc to reach the client connected via openvpn.  Tried to replace the openvpn network with a ipvlan which works for the vpn (macvlan appears as an option via portainer but doesn't save), but I've still been unable to reach the mobile device from my home network.  I have a lot of experience but cannot be sure to have tried 100% of all possibilities on this one.

**Comment by aptalca** [comment]
Add your lan subnets to the Openvpn gui settings under network

**Comment by karezza** [comment]
I did this and still not working.  Are you giving an idea that might work or can you say for sure this does work?

**Comment by karezza** [comment]
Tried reinstalling OS from scratching, installing docker, then using 'docker run' rather than the docker-compose method, added in '--network=host' but still was able to get it to work.  I'm just not sure if it's impossible to get this to work based on how the image is setup or if it's just something I need to configure.  I located this URL which seems like it might be the solution if the image will work:  https://openvpn.net/vpn-server-resources/reach-openvpn-clients-directly-from-a-private-network/

**Comment by aptalca** [comment]
#149
