### ISSUE TITLE
Don't delete SSL certificates & keys on upgrade

### ISSUE THREAD

**Issue by pseudocoder** [linuxserver-archive/docker-openvpn-as#144]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Don't delete the content of /config/etc/web-ssl on upgrade, so externally provided certs still work

## Current Behavior
Line 43 in /root/etc/cont-init.d/30-config deletes the web-ssl folder

i.e. change this line to include web-ssl in the folders excluded.

## Alternatives Considered
Maybe use another volume mounted to the host location of the certificates and a custom script to copy them over on init; but this breaks the encapsulation - I want the host to put the certs into the container, not the other way round.

**Comment by aptalca** [comment]
#149
