### ISSUE TITLE
OpenVPN connection OK, but cannot access local resources or Internet at all?

### ISSUE THREAD

**Issue by jamesngob** [linuxserver-archive/docker-openvpn-as#145]
Hello everyone,
I am very new to the world Docker/Container so thank you in advance for your patience
I recently delploy OpenVPN-AS docker using Rancher. Then I created new user to test.
On my iPhone, I can initial the connection and the openvpn app showed "connected"
However, from there, I cannot access any local resources (like my NAS) nor the Internet

My host IP is 10.9.9.26, which is a virtual Ubuntu Server installed on ESXi. I did use the variable
"INTERFACE" = eth0: does not work
"INTERFACE" = 10.9.9.26: does not work
Leave blank: does not work

I must have missed something in this config. Could anyone point me out?
Thank you

**Comment by aptalca** [comment]
#149
